### ISSUE TITLE
 loss = criterion(output[selected], torch.tensor(labels_selected).long() -1)  ValueError: too many dimensions 'str'

### ISSUE THREAD

**Issue by rashibudati** [plkmo/Bible_Text_GCN#2]
I am trying to run the code on my dataset. Its a public dataset having text and the respective class name. The text for each class name is about one line. 
Do I need to change the code because I don't have the header like you have in yours?

**Comment by plkmo** [comment]
The class name should be an int, not a str. Eg. for two classes, class name will be 0, 1.

Its not convenient to run your own dataset here, as u need to modify the pre-processing code since the original Bible dataset format is quite different. If you want to run on your own dataset, you can run on my other repo https://github.com/plkmo/NLP_Toolkit#1-classification which has a sample IMDB dataset whose formatting you can follow, also mentioned in the documentation.

**Comment by rashibudati** [comment]
Okay, thanks!
